### ISSUE TITLE
Public repository

### ISSUE THREAD

**Issue by rowan-mcalpin** [trc492/Ftc2024CenterStage#1]
Hi, folks! I'm the lead programmer of Atomic Robotics (team 3805). I just thought I'd let you know that your repository is public. If this is intended, carry on-- see you at competitions! I know a lot of teams keep their code private, though, so I thought I'd let you know. 

Good luck for this season, it's got some pretty unique challenges and I'm excited to see everyone's solutions for them.

~Rowan, 3805 software lead

**Comment by trc492** [comment]
Yes, that's intentional. Our code is always open source, but thanks for the heads up.
